- name: Render template configurations
  ansible.builtin.template:
    src: system.yaml.j2
    dest: "{{ k9s_source_dir }}/skins/system.yaml"
    owner: "{{ ansible_facts['ansible_user_id'] }}"
    group: "{{ ansible_facts['ansible_user_id'] }}"
    mode: "0600"
  tags: [k9s, config]

- name: Copy file configurations
  ansible.builtin.copy:
    src: config.yaml
    dest: "{{ k9s_source_dir }}/config.yaml"
    owner: "{{ ansible_facts['ansible_user_id'] }}"
    group: "{{ ansible_facts['ansible_user_id'] }}"
    mode: "0600"
  tags: [k9s, config]
