- name: Create source directory
  ansible.builtin.file:
    path: "{{ hyprland_source_dir }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  become: true
  tags: [hyprland, config]

- name: Render template configurations
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ hyprland_source_dir }}/{{ item }}"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  loop:
    - hypridle.conf
    - hyprland.conf
    - hyprlock.conf
  tags: [hyprland, config]

- name: Enable polkitagent
  ansible.builtin.systemd_service:
    name: hyprpolkitagent.service
    enabled: true
    state: restarted
  tags: [polkitagent, systemd]

- name: Enable hypridle
  ansible.builtin.systemd_service:
    name: hypridle.service
    enabled: true
    state: restarted
  tags: [hypridle, systemd]
