- name: Render template configurations
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ yazi_source_dir }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  loop:
    - syntect.tmTheme
    - theme.toml
    - yazi.toml
  tags: [yazi, config]
