- name: Create source directory
  ansible.builtin.file:
    dest: "{{ yazi_source_dir }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  tags: [yazi, config]

- name: Render template configurations
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ yazi_source_dir }}/{{ item }}"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  loop:
    - syntect.tmTheme
    - theme.toml
    - yazi.toml
  tags: [yazi, config]
