- name: Render template configurations
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ kitty_source_dir }}/{{ item }}"
    owner: "{{ ansible_facts['ansible_user_id'] }}"
    group: "{{ ansible_facts['ansible_user_id'] }}"
    mode: "0600"
  loop:
    - kitty.conf
    - theme.conf
  tags: [kitty, config]
