- name: Copy file configurations
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ git_source_dir }}/{{ item }}"
    owner: "{{ ansible_facts['ansible_user_id'] }}"
    group: "{{ ansible_facts['ansible_user_id'] }}"
    mode: "0600"
  loop:
    - config
  tags: [git, config]
