- name: Render template configurations
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ rofi_source_dir }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  loop:
    - config.rasi
  tags: [rofi, config]
