- name: Create source directory
  ansible.builtin.file:
    path: "{{ rofi_source_dir }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  become: true
  tags: [rofi, config]

- name: Render template configurations
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ rofi_source_dir }}/{{ item }}"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  loop:
    - config.rasi
  tags: [rofi, config]
