- name: Render template configurations
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ waybar_source_dir }}/{{ item }}"
    owner: "{{ ansible_facts['ansible_user_id'] }}"
    group: "{{ ansible_facts['ansible_user_id'] }}"
    mode: "0600"
  loop:
    - config
    - style.css
  tags: [waybar, config]

- name: Copy file configurations
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ waybar_source_dir }}/{{ item }}"
    owner: "{{ ansible_facts['ansible_user_id'] }}"
    group: "{{ ansible_facts['ansible_user_id'] }}"
    mode: "0600"
  loop:
    - waybar-modules-custom.jsonc
    - waybar-modules-groups.jsonc
    - waybar-modules.jsonc
    - waybar-modules-workspaces.jsonc
  tags: [waybar, config]
