- name: Create theme directory
  ansible.builtin.file:
    path: "{{ btop_source_dir }}/themes"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  become: true
  tags: [btop, config]

- name: Render template configurations
  ansible.builtin.template:
    src: system.yaml.j2
    dest: "{{ btop_source_dir }}/themes/system.theme"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  tags: [btop, config]

- name: Copy file configurations
  ansible.builtin.copy:
    src: btop.conf
    dest: "{{ btop_source_dir }}/btop.conf"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  tags: [btop, config]
