- name: Create source directory
  ansible.builtin.file:
    path: "{{ bat_source_dir }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  become: true
  tags: [bat, config]

- name: Create theme directory
  ansible.builtin.file:
    path: "{{ bat_source_dir }}/themes"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  become: true
  tags: [bat, config]

- name: Render template configurations
  ansible.builtin.template:
    src: system.tmTheme.j2
    dest: "{{ bat_source_dir }}/themes/system.tmTheme"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  tags: [bat, config]

- name: Copy file configurations
  ansible.builtin.copy:
    src: config
    dest: "{{ bat_source_dir }}/config"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0600"
  tags: [bat, config]
